name: Release

on:
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: 'Version type'
        required: true
        default: 'patch'
        options:
          - major
          - minor
          - patch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Test
        timeout-minutes: 1
        run: ssh -T git@github.com
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          architecture: x64
          cache: 'maven'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Initialize Git
        timeout-minutes: 1
        run: |
          git config --global user.name 'Matus Faro'
          git config --global user.email 'matus@matus.io'
      - name: Maven release
        timeout-minutes: 60
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make release-${{ github.event.inputs.versionType }}